### ISSUE TITLE
`AttributeError: Can't pickle local object 'get_app.<locals>.App'`

### ISSUE THREAD

**Issue by lethal233** [Mondego/spacetime-crawler4py#33]
Hi guys,

When I run this project I met this problem:
```python
Traceback (most recent call last):
  File "D:\Projects\assignment2-crawler\launch.py", line 23, in <module>
    main(args.config_file, args.restart)
  File "D:\Projects\assignment2-crawler\launch.py", line 13, in main
    config.cache_server = get_cache_server(config, restart)
  File "D:\Projects\assignment2-crawler\utils\server_registration.py", line 27, in get_cache_server
    return init_node.start(
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\site-packages\spacetime\node.py", line 108, in start
    self._start(*args, **kwargs)
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\site-packages\spacetime\node.py", line 102, in _start
    super().start()
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\xxxx\.conda\envs\assignment2-crawler\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_app.<locals>.App'
```

Could you please help me with this issue?

Best

**Comment by JsperGoBananas** [comment]
Hi, how did you resolve this problem at last?
